# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package files first for better caching
COPY package*.json ./

# Install dependencies
RUN npm ci

# Install the Vendure CLI globally in the container
RUN npm install -g @vendure/cli

# Copy the rest of the application code
COPY . .

# Build the dashboard
RUN npx vite build

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Run the command to start the app in dev mode
CMD ["npm", "run", "dev"]